export component MainWindow {
    width: 800px;
    height: 800px;

    HorizontalLayout {
        padding: 20px;
        spacing: 10px;
        alignment: center;  // Centers the layout vertically
        
        Text {
            text: "test";
            font-size: 30px;
            color: white;
        }
        Text {
            text: "test";
            font-size: 30px;
            color: white;
        }
    }
}